version: 46
jobs:
- name: Push to Mirrors
  steps:
  - type: PushRepository
    name: Mirror to github.com
    remoteUrl: https://github.com/zuedev/gitinfo
    userName: zuedev
    passwordSecret: github-access-token
    force: true
    condition: SUCCESSFUL
    optional: false
  - type: PushRepository
    name: Mirror to gitlab.docker-compose.zue.dev
    remoteUrl: https://gitlab.docker-compose.zue.dev/zuedev/gitinfo.git
    userName: zuedev
    passwordSecret: gitlab.docker-compose-access-token
    force: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    userMatch: anyone
  - type: TagCreateTrigger
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
